CREATE TABLE IF NOT EXISTS public.gallery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url TEXT NOT NULL,
    alt_text TEXT,
    sort_order INTEGER DEFAULT 0,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.gallery ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist to avoid errors on re-run
DROP POLICY IF EXISTS "Allow public read access" ON public.gallery;
DROP POLICY IF EXISTS "Allow all access for authenticated users" ON public.gallery;

-- Allow public read access
CREATE POLICY "Allow public read access" ON public.gallery FOR SELECT USING (TRUE);

-- Allow all access for authenticated users (admins)
CREATE POLICY "Allow all access for authenticated users" ON public.gallery FOR ALL USING (auth.role() = 'authenticated');
